contacts:
  name: Nico D'Cotta
  title: Backend Software Engineer
  email: nico@dcotta.com
  address: "London, UK"
  location: London, UK
  linkedin:
    url: https://linkedin.com/in/ndcotta
    displayText: linkedin.com/in/ndcotta
  github:
    url: https://github.com/cottand
    displayText: github.com/cottand
  website:
    url: https://nico.dcotta.com
    displayText: nico.dcotta.com

position: Backend Software Engineer

tagline: Backend Software Engineer with experience in building and scaling distributed systems, with a focus on security, payments, and financial services.

jobs:
  - position: Senior Backend Software Engineer
    company:
      name: Monzo Bank
      link: https://monzo.com
    product:
      name: Payments & Security
      link: https://monzo.com
    description:
      - Worked both on Payments as building products for retail customers, and in Security in an SRE-heavy role with wide scope.
      - Owned secret-management, public-key infrastructure, and preventive and detective security controls (eg. around intrusion, exfiltration, DDoS, etc).
      - Maintained critical zero-downtime infrastructure such as Kubernetes, cloud networking, and sensitive key material management.
    from: "11/23"
    to: "today"
    tags:
      - Security
      - Payments
      - SRE
    location: London, UK
  - position: Senior Backend Software Engineer
    company:
      name: Blockchain.com
      link: https://blockchain.com/about
    product:
      name: Financial Services
      link: https://blockchain.com
    description:
      - Owned several JVM (mainly Kotlin) real-time financial services critical for business operation and central to user experience and transaction auditing; like ledger-keeping/accounting and indicative pricing.
      - Designed and scaled up stateful distributed systems with an event-driven architecture.
      - Reviewed systems' architecture designs and software development methods to cultivate sustainable engineering practices and achieve operational excellence within the wider company.
    from: "06/20"
    to: "11/23"
    tags:
      - JVM
      - Kotlin
      - Distributed Systems
    location: London, UK
  - position: Software Engineer
    company:
      name: Emit, Inc.
      link: ""
    product:
      name: Time Analytics
      link: ""
    description:
      - Four-person startup with its own smartwatch aiming to provide time-analytics to institutional customers.
      - Provided real-time insights on customer data by developing data processing pipelines and libraries in Kotlin and Python on top of serverless tech on AWS (Lambda, DynamoDB, ElasticSearch).
    from: "06/19"
    to: "10/19"
    tags:
      - Kotlin
      - Python
      - AWS
    location: London, UK

objective: Backend Software Engineer with experience in building and scaling distributed systems, with a focus on security, payments, and financial services.

education:
  - place:
      name: Imperial College London
      link: "https://www.imperial.ac.uk/"
    degree: "MEng"
    major: Computer Science
    track: First Class Honours
    from: "2018"
    to: "2022"
    location: London, UK
  - place:
      name: French Lycée of Madrid
      link: ""
    degree: "French Baccalaureate"
    major: S-SI
    track: Highest Honours
    from: "2015"
    to: "2018"
    location: Madrid, Spain

technical_expertise:
  - name: Go
    level: 5
  - name: Kotlin
    level: 5
  - name: Java
    level: 4
  - name: Nix + NixOS
    level: 5
  - name: Gradle
    level: 4
  - name: Python
    level: 3

skills:
  - C
  - Haskell
  - Typescript
  - Elixir
  - Nomad
  - Kubernetes
  - Consul
  - Vault
  - Terraform
  - AWS (IAM, EC2, S3, WAF + Shield, DynamoDB)
  - gRPC + protobufs
  - Kafka
  - Akka
  - PostgreSQL
  - Redis
  - Cassandra
  - APM
  - Docker
  - React

methodology:
  - Object-oriented programming
  - Functional programming
  - Actor-oriented programming
  - Procedural programming

tools:
  - AWS
  - Kubernetes
  - Nomad
  - Terraform
  - Docker
  - Git

achievements:
  - name: "Languages"
    description: "English - bilingual, Spanish - native, French - bilingual, Portuguese - advanced level"
  - name: "Skills + Feedback"
    description: "\"Pleasant to work with\", \"Aware of product quality\", \"Knows which battles to pick\", I can google well!"
  - name: "Hobbies"
    description: "I enjoy gardening as well as kitesurfing and rock climbing"
  - name: "Portfolio"
    description: "See my full portfolio at nico.dcotta.com/projects"

projects:
  - name: "Self-hosted infrastructure"
    link: "https://nico.dcotta.com/projects/selfhosted-homelab"
    technologies: "Nomad, NixOS, Golang"
    description: "A HA self-hosted cluster with all the features you can expect from an enterprise-grade platform, including container orchestration, service discovery, a service mesh, a distributed filesystem, etc."
  - name: "DJStreamr, collaborative streaming service for DJs"
    link: "https://djstreamr.com"
    technologies: "AWS (Lambda, DynamoDB, EC2), Kotlin, VueJS"
    description: "Music synchronisation protocol implemented as a webapp with an event-driven platform architecture which leverages serverless technology."
  - name: "Multi-Paxos implementation"
    link: "https://github.com/cottand/multi-paxos"
    technologies: "Elixir, Paxos"
    description: "Implementation of a variation of the Paxos consensus algorithm (comparable to Raft), as specified in the paper Paxos Made Moderately Complex."
  - name: "WACC, multiplatform compiler"
    link: "https://github.com/cottand/WACC"
    technologies: "Kotlin, JVM bytecode, ARM11 assembly"
    description: "Multiplatform compiler for WACC (a toy language) to JVM bytecode and ARM11 64-byte assembly that supports basic constructs like stack-allocated primitives, and heap-allocated arrays and pairs."
